apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivashko-face-verification-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-verification
  template:
    metadata:
      labels:
        app: face-verification
    spec:
      containers:
      - name: face-verification
        image: merewhale/face_verification
        env:
        - name: PYTHONPATH
          value: /workspace/src/app
        - name: KAFKA_HOST
          value: infro-kafka-controller-headless:9092
        - name: POSTGRES_HOST
          value: http://postgres-service:5432
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: iivashko
        ports:
        - containerPort: 8003

